### ISSUE TITLE
Icinga graphite writer perfdata error

### ISSUE THREAD

**Issue by ghost** [iamcheko/check_snmp_interface#2]
Hello. Graphite writer refuses to write performance data with error: 

[2016-01-29 11:25:09 +0500] warning/GraphiteWriter: Ignoring invalid perfdata value: FastEthernet0/4_ifinoctets=19686.00Bps;90.00;97.00;0;12500000

I think the problem is that there is no support "Bps" unit in graphite writer.

**Comment by iamcheko** [comment]
Hi, sorry for the late response, I wasn't aware that anybody would use this plugin ;). Well I updated the script. Now the performance data is "bps", I hope graphite supports bps else let me know what units graphite would expect.

**Comment by ghost** [comment]
Hello. I think he using the units from "monitoring plugins development guidlines".
Unit is one of:
1. no unit specified - assume a number (int or float) of things (eg, users, processes, load averages)
2. s - seconds (also us, ms)
3. % - percentage
4. B - bytes (also KB, MB, TB)
5. c - a continous counter (such as bytes transmitted on an interface)
Here is the link:  https://www.monitoring-plugins.org/doc/guidelines.html#AEN201

**Comment by iamcheko** [comment]
Thats bad news. Pnp4nagios support all kind of units and thats good, since traffic could also be packets. But I understand your need and I implemented a feature to suppress the uom and instead put it into the label. Hope that works for you.

**Comment by iamcheko** [comment]
The argument is called --suppressuom. the generated performance data looks like this:
'eth0_ifinoctets_in_bps'=100.00;;... and so on

**Comment by ghost** [comment]
I had error:
crazyscientist@icinga:/tmp$ /usr/lib/nagios/plugins/check_snmp_interface -h
syntax error at /usr/lib/nagios/plugins/check_snmp_interface line 1167, near "my "
Global symbol "$uom" requires explicit package name at /usr/lib/nagios/plugins/check_snmp_interface line 1167.
Global symbol "$uom" requires explicit package name at /usr/lib/nagios/plugins/check_snmp_interface line 1173.
Global symbol "$uom" requires explicit package name at /usr/lib/nagios/plugins/check_snmp_interface line 1194.
Global symbol "$uom" requires explicit package name at /usr/lib/nagios/plugins/check_snmp_interface line 1195.
Global symbol "$uom" requires explicit package name at /usr/lib/nagios/plugins/check_snmp_interface line 1199.
Global symbol "$uom" requires explicit package name at /usr/lib/nagios/plugins/check_snmp_interface line 1200.
Execution of /usr/lib/nagios/plugins/check_snmp_interface aborted due to compilation errors.

**Comment by iamcheko** [comment]
Sorry, my bad. Don't know when i pushed this version back. Well there is a fix available.

**Comment by ghost** [comment]
Argument don't work:
crazyscientist@icinga:/tmp$ /usr/lib/nagios/plugins/check_snmp_interface --suppressuom -H 192.168.1.4 -i FastEthernet0/3 
Unknown option: suppressuom

**Comment by iamcheko** [comment]
Its --suppressunit.

**Comment by ghost** [comment]
Script works. Thx.

**Comment by iamcheko** [comment]
Thank you for your patience and sorry again for this fail compilation.
