### ISSUE TITLE
SNMP V3 typo in parameternames

### ISSUE THREAD

**Issue by mdicss** [iamcheko/check_snmp_interface#7]
Hi Marek

Wir machen den Update auf snmp v3. Im Skript sind 2 Namen falsch:
Die Zeilen 1197 und 1198 sollten wie folgt sein:
                $options->{ Privpassword }    = $np->opts->privpass;
                $options->{ PrivProtocol }    = $np->opts->privproto;

Gruss
Matthias

**Comment by iamcheko** [comment]
Thanks for your information. I applied the change. Feel free to test.
